
title: <p align="center"> Yannis Montreuil </p>

logo: "/images/test222.png?raw=true"

description:
  <p align="center">
  <a href="pdf/CV_MONTREUIL_NP_2p_Version_advice_bk(5).pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/yannis-montreuil/">LinkedIn</a> |
  <a href="https://github.com/Yannis-98">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing MS degree in Robotics focus on Deep-Learning and Computer Vision, at Sorbonne University and Arts et MÃ©tiers Paris.
  <br><br>
  I am currently looking for a Ph.D. position to study Deep-Learning algorithms for Computer Vision problems.
  <br><br>
  </p>
  
  Deep-Learning and Computer Vision
  <p style="margin-left:10%; margin-right:10%;">This is the text that I want to indent. I want to create a margin on both sides so that it doesn't go the full width of the page. Don't ask me why I want to do this. I just do!</p>


 
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
