
title: <p align="center"> Yannis Montreuil </p>

logo: "/images/test222.png?raw=true" 

description:
  <p align="center">
  <a href="pdf/CV_MONTREUIL_NP_2p_Version_advice_bk(5).pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/yannis-montreuil/">LinkedIn</a> |
  <a href="https://github.com/Yannis-98">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing MSc degree in Robotics focus on Deep-Learning and Computer Vision, at Sorbonne University and Arts et MÃ©tiers Paris.
  <br><br>
  I am currently looking for a Ph.D. position to study Deep-Learning algorithms for Computer Vision problems.
  </p>
  
  <a href=""> Deep-Learning and Computer Vision</a>
  <p style="margin-left:10%;">Overlapped Fingerprints<br>
  Accident Anticipation<br>
  Semi-supervised algorithms<br>
  Autonomous UAV<br>
  Colorization Transformer<br>
  Image Inpaiting<br>
  Particle Tracking</p>
  <a href="">Optimization</a>
  <p style="margin-left:10%;">Propeller optimization, airship UAV<br>
  Heat Exchanger Optimization</p>
  <a href="">Reinforcement Learning</a>
  <p style="margin-left:10%;">Lunar Landing</p>

  




 
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
