title: <p align="center"> Chris Tran </p>

logo: "/images/test222.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/yannis-montreuil/">LinkedIn</a> |
  <a href="https://github.com/Yannis-98">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing MS degree in Robotics focus on Deep-Learning and Computer Vision, at Sorbonne University and Arts et MÃ©tiers Paris.
  <br><br>
  I am currently looking for a Ph.D. position to study Deep-Learning algorithms for Computer Vision problems.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
