
title: <p align="center"> Yannis Montreuil </p>

logo: "/images/test222.png?raw=true"

description:
  <p align="center">
  <a href="pdf/CV_MONTREUIL_NP_2p_Version_advice_bk(5).pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/yannis-montreuil/">LinkedIn</a> |
  <a href="https://github.com/Yannis-98">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing MS degree in Robotics focus on Deep-Learning and Computer Vision, at Sorbonne University and Arts et MÃ©tiers Paris.
  <br><br>
  I am currently looking for a Ph.D. position to study Deep-Learning algorithms for Computer Vision problems.
  <br><br>
  </p>
  Deep-Learning and Computer Vision
  <p style="margin-left:10%; margin-right:10%;">Separating Latent Overlapped Fingerprints</p>
  <p style="margin-left:10%; margin-right:10%;">Accident Anticipation and Risky Region Localization</p>
  <p style="margin-left:10%; margin-right:10%;">Semi-supervised algorithms and image augmentations for the segmentation of satellite images</p>
  <p style="margin-left:10%; margin-right:10%;">Autonomous UAV Dassault UAV Challenge</p>
  <p style="margin-left:10%; margin-right:10%;">Colorization Transformer by Google</p>
  <p style="margin-left:10%; margin-right:10%;">Image Inpaiting</p>
  <p style="margin-left:10%; margin-right:10%;">Particle Tracking</p>
  Optimization
  <p style="margin-left:10%; margin-right:10%;">Propeller optimization, airship UAV</p>
  <p style="margin-left:10%; margin-right:10%;">Heat Exchanger Optimization</p>
  Reinforcement Learning
  <p style="margin-left:10%; margin-right:10%;">Lunar Landing</p>

  




 
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
